# Generated by Django 3.2.6 on 2021-08-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
