# Generated by Django 3.2.6 on 2021-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default=None, help_text='select None', max_length=20),
        ),
    ]
